x = int(input("Enter the 1st no."))
y = int(input("Enter the 2nd no."))
z = int(input("Enter the 3rd no."))
a1 = max(x,y,z)
a2 = min(x,y,z)
a3 = (x+y+z)-(a1+a2)
a1 = str(a1)
a2 = str(a2)
a3 = str(a3)
print(a1+">"+a3+">"+a2)
